#!/bin/bash

# SIZE = 24576 -> 24 

if [ ! -f "$1" ]; then
    echo "No file $1"
    exit -1
fi

copyto="$1.spl_1kchunked"
if [ $# -gt 1 ]; then
    copyto=$2
fi

tmpdir=$(mktemp -d)

dd if=/dev/zero of=$tmpdir/chunked bs=1024 count=24  > /dev/null 2>&1


echo "Copying block 0 to 0"
dd if=$1 of=$tmpdir/chunked bs=1024 count=2 seek=0 skip=0 conv=notrunc > /dev/null 2>&1

for from in `seq 1 23`;
do
	let to=$from*2-1
	let dub=$from*2
	echo "Copying block $from to $to"
	echo "Copying block $from to $dub" 
	dd if=$1 of=$tmpdir/chunked bs=1024 count=1 seek=$to skip=$from conv=notrunc > /dev/null 2>&1
	dd if=$1 of=$tmpdir/chunked bs=1024 count=1 seek=$dub skip=$from conv=notrunc > /dev/null 2>&1
done

dd if=$1 of=$tmpdir/chunked bs=1024 seek=48 skip=24 > /dev/null 2>&1

mv $tmpdir/chunked $copyto

rm -rf $tmpdir
